apiVersion: v1
kind: Service
metadata:
  name: web-service-f
  labels:
    name: web-f
    app: todoapp-f
spec:
  selector:
    name: web-f
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 
      nodePort: 30002
     protocol: TCP
