apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-f
spec:
  selector:
    matchLabels:
      name: web-f
  template:
    metadata:
      labels:
        name: web-f
        app: todoapp-f
    spec:
      containers:
        - image: terezabisharyan/app-frontend:35d591c90677f7e1c520d4b8b87fa4b0e1f27d42
          imagePullPolicy: Always
          name: myweb
          ports:
            - containerPort: 80
          #env:
          #- name: REACT_APP_BASE_URL
            #value: http://web-service.default.svc.cluster.local
