apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-f
spec:
  selector:
    matchLabels:
      name: web-f
  template:
    metadata:
      labels:
        name: web-f
        app: todoapp-f
    spec:
      containers:
        - image: terezabisharyan/app-frontend:3daacee0527fffd8f294bac23194125ef5324119
          imagePullPolicy: Always
          name: myweb
          ports:
            - containerPort: 3000
          #env:
          #- name: REACT_APP_BASE_URL
            #value: http://web-service.default.svc.cluster.local
