apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-f
spec:
  selector:
    matchLabels:
      name: web-f
  template:
    metadata:
      labels:
        name: web-f
        app: todoapp-f
    spec:
      containers:
        - image: terezabisharyan/app-frontend:a3496e6689c1409a4ca4c299e91e3e16ea28511c
          imagePullPolicy: Always
          name: myweb
          ports:
            - containerPort: 80
          #env:
          #- name: REACT_APP_BASE_URL
            #value: http://web-service.default.svc.cluster.local
